### ISSUE TITLE
Bagus

### ISSUE THREAD

**Issue by cahya-wirawan** [nunenuh/iqradre_reader#1]
Kelihatannya bagus nih project nya :-) cuma kalau boleh saya bagi pendapat, lebih baik tidak mencantumkan data pribadi spt foto ktp di public repository, supaya tidak di salah gunakan nanti nya. Atau apakah itu fake fotonya? :-)

**Comment by nunenuh** [comment]
thanks mas, I'm lonely wolf, sometime I forgot about this. The data has been removed by the way
